name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Notify pkg.go.dev
        run: make pkg-go-dev VERSION=${{ github.ref_name }}
      - uses: actions/checkout@v4
