name: tests

on:
  push:
    branches:
      - main
    paths:
      - '*'
      - '.github/workflows/tests.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '*'
      - '.github/workflows/tests.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go Faster
        uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: 1.22.5

      - name: Perform Tests
        run: make test
